v2/todolist/todo/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name="index"),
    path('update/<int:id>', views.update, name='update_task'),
    path('delete/<int:id>', views.delete, name='delete_task')
]

v2/todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls"))
]

v2/todolist/todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    time_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} -> {self.time_added}'

v2/todolist/todo/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from .models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

v2/todolist/todo/views.py
from django.http import request
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls.base import reverse
from .models import *
from .forms import TaskForm

def index(request):
    alltasks = Task.objects.all().order_by('-time_added')

    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {'alltasks': alltasks, "form":form}
    return render(request, "todo/index.html", context)

def update(request, id):
    currTask = Task.objects.get(id=id)

    form = TaskForm(instance=currTask)
    if request.method=='POST':
        form = TaskForm(request.POST, instance=currTask)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse("todos:index"))

    context = {'form': form, 'currTask': currTask}
    return render(request, 'todo/update.html', context)

def delete(request, id):
    task = Task.objects.filter(id=id)
    if task:
        task.delete()
    return HttpResponseRedirect(reverse("todos:index"))

v2/todolist/todo/templates/todo/index.html
{% extends "todo/layout.html" %}

{% block body %}

<div class="center-column">
    <h1 style="text-align: center;">Todo App </h1>
    <h4>Enter Tasks Below</h4>
<form method="POST" action="{% url 'todos:index' %}" autocomplete="off">
    {% csrf_token %}
    {{ form.title }}
    <input type="submit" value="Add Task">
</form>

<div class="todo-list">
{% for item in alltasks %}  
        <div class="item-row">
            
            {% if item.complete == True %}
                <strike>{{ item.title }}</strike>
                <small>{{ item.time_added|date:"F d, Y" }}</small>
            {% else %}
                <span>{{ item.title }}</span>
                <small>{{ item.time_added|date:"F d, Y" }}</small>
            {% endif %}

            <a class="btn btn-sm btn-info" href="{% url 'todos:update_task' item.id %}">Update</a>
            <form action=" {% url 'todos:delete_task' item.id %}">
                <button type="submit" class="btn btn-primary btn-sm btn-danger">Delete</button>
            </form>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

v2/todolist/todo/templates/todo/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo List</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'todo/styles.css' %}">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
            <link rel="stylesheet" href="{% static 'todo/styles.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

v2/todolist/todo/templates/todo/update.html
{% extends 'todo/layout.html' %}

{% block body %}
<style>
    * {
        margin: 15px;
    }
</style>
<h3>Update Task</h2>
<form method="POST" action="{% url 'todos:update_task' currTask.id %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="Update">
</form>
{% endblock %}